version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python py/utils/download_chromedriver.py --os=linux && pip install -r requirements.txt && python run.py"
